/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ura_test_JNItest */

#ifndef _Included_com_bjw_gpio_GPIOJNI
#define _Included_com_bjw_gpio_GPIOJNI
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
